[mgr]
show_hidden    = true
sort_dir_first = true
sort_by = "mtime"
sort_reverse = false

[preview]
max_width = 1200
max_height = 1000
tab_size        = 2
cache_dir       = ""
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
edit = [
	{ run = 'nvim "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'open "$@"', desc = "Open" },
]
