import = []

[[session]]
name = "home ğŸ "
path = "~"

[[session]]
name = "code ğŸ’»"
path = "~/code"

[[session]]
name = "dotfiles âš™ï¸"
path = "~/dotfiles"
startup_command = "nvim"

[[session]]
name = "mono ğŸ’¼"
path = "~/code/komodor/mono"

[[session]]
name = "gh-dash ğŸš€"
path = "~/code/personal/gh-dash"

[[session]]
name = "downloads ğŸ“‚"
path = "~/Downloads"
startup_command = "e"
