# yaml-language-server: $schema=https://gh-dash.dev/schema.json
prSections:
  - title: Mine
    filters: is:open author:@me -repo:microsoft/vscode
    layout:
      author:
        hidden: true
  - title: Review
    filters: is:open review-requested:@me
    layout:
      repo:
        width: 6
  - title: gh-dash
    filters: "is:open repo:dlvhdr/gh-dash"
  - title: Commented
    filters: commenter:@me
  - title: Subscribed
    filters: "\
      repo:nvim-telescope/telescope.nvim \
      repo:ldelossa/gh.nvim \
      repo:neovim/neovim \
      repo:withgraphite/graphite-cli \
      repo:cli/cli"
  - title: LSP
    filters: "-author:app/dependabot -author:app/github-action \
      repo:TypeFox/monaco-languageclient \
      repo:typescript-language-server/typescript-language-server \
      repo:CodinGame/monaco-vscode-api"
issuesSections:
  - title: Creator
    filters: author:@me
  - title: Commented
    filters: is:open commenter:@me
  - title: dlvhdr
    filters: org:dlvhdr
  - title: gh-dash
    filters: is:open repo:dlvhdr/gh-dash
  - title: Assigned
    filters: is:open assignee:@me

pager:
  diff: diffnav
defaults:
  view: prs
  refetchIntervalMinutes: 10
  layout:
    prs:
      repoName:
        grow: true,
        width: 10
        hidden: false
      base:
        hidden: true

  preview:
    open: true
    width: 70
  prsLimit: 20
  issuesLimit: 20
repoPaths:
  port-labs/Port: ~/code/port/mono
  port-labs/*: ~/code/port/*
  dlvhdr/*: ~/code/personal/*

keybindings:
  universal:
    - key: g
      name: lazygit
      command: >
        cd {{.RepoPath}} && lazygit
  prs:
    - key: C
      builtin: checkout
    - key: m
      command: gh pr merge --admin --repo {{.RepoName}} {{.PrNumber}}
    - key: O
      name: code review
      command: >
        tmux new-window -c {{.RepoPath}} -n "octo" '
        nvim -c ":silent Octo pr edit {{.PrNumber}}"
        '
    - key: T
      command: >-
        tmux new-window -n "enhance" '
          gh enhance -R {{.RepoName}} {{.PrNumber}}
        '
    - key: v
      name: approve
      command: >
        gh pr review --repo {{.RepoName}} --approve --body "$(gum input --prompt='Approval Comment: ')" {{.PrNumber}}

theme:
  ui:
    sectionsShowCount: true
    table:
      compact: false
  colors:
    text:
      primary: "#E2E1ED"
      secondary: "#666CA6"
      inverted: "#242347"
      faint: "#B0B3BF"
      warning: "#E0AF68"
      success: "#3DF294"
    background:
      selected: "#1B1B33"
    border:
      primary: "#383B5B"
      secondary: "#39386B"
      faint: "#2B2B40"
